### ISSUE TITLE
feat: auto decode the calldata using brownie?

### ISSUE THREAD

**Issue by gosuto-inzasheru** [Badger-Finance/gnosis-multisig-monitor#4]
not sure if it is possible to integrate, but would save reviewers a lot of time

**Comment by gosuto-inzasheru** [comment]
```
>>> Contract.from_explorer("address").decode_input("data")
```

**Comment by petrovska-petro** [comment]
look into thread creation if doable *

**Comment by petrovska-petro** [comment]
since now gnosis UI already has out of the box tenderly sim, advising to close this ticket

**Comment by petrovska-petro** [comment]
closing in favour of leveraging the tenderly sim feature and looking for pro-active signers to do the DD at their end locally
